### ISSUE TITLE
crash when trying to play standard mode

### ISSUE THREAD

**Issue by Timtam** [Wensber/TextTheSpire#23]
Hello,

I just recently played the first ascension the silent and finished it with the victory over act 3 (act 4 not yet unlocked). I then wanted to play it today, after updating to latest TextTheSpire 1.22.
I'm not sure if it has to do with the newest update however.
Whenever I press "play" and then "standard", the entire game crashes and I can see the following within the logs:
```
08:44:39.124 ERROR basemod.ReflectionHacks> Exception occurred when getting private field allOptions of basemod.CustomCharacterSelectScreen
java.lang.IllegalArgumentException: Can not set java.util.ArrayList field basemod.CustomCharacterSelectScreen.allOptions to com.megacrit.cardcrawl.screens.charSelect.CharacterSelectScreen
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:1.8.0_144]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:1.8.0_144]
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:1.8.0_144]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36) ~[?:1.8.0_144]
	at java.lang.reflect.Field.get(Field.java:393) ~[?:1.8.0_144]
	at basemod.ReflectionHacks.getPrivate(ReflectionHacks.java:228) [BaseMod.jar:?]
	at textTheSpire.Choices.getText(Choices.java:739) [TextTheSpire-win64.jar:?]
	at textTheSpire.AbstractWindow.update(AbstractWindow.java:11) [TextTheSpire-win64.jar:?]
	at textTheSpire.Choices.update(Choices.java:65) [TextTheSpire-win64.jar:?]
	at textTheSpire.TextTheSpire.receivePostUpdate(TextTheSpire.java:2714) [TextTheSpire-win64.jar:?]
	at basemod.BaseMod.publishPostUpdate(BaseMod.java:2354) [?:?]
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.UpdateHooks$PostUpdateHook.Insert(UpdateHooks.java:52) [BaseMod.jar:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:892) [?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:419) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
08:44:39.132 INFO core.CardCrawlGame> Exception occurred in CardCrawlGame render method!
08:44:39.133 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at textTheSpire.Choices.getText(Choices.java:740) ~[TextTheSpire-win64.jar:?]
	at textTheSpire.AbstractWindow.update(AbstractWindow.java:11) ~[TextTheSpire-win64.jar:?]
	at textTheSpire.Choices.update(Choices.java:65) ~[TextTheSpire-win64.jar:?]
	at textTheSpire.TextTheSpire.receivePostUpdate(TextTheSpire.java:2714) ~[TextTheSpire-win64.jar:?]
	at basemod.BaseMod.publishPostUpdate(BaseMod.java:2354) ~[?:?]
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.UpdateHooks$PostUpdateHook.Insert(UpdateHooks.java:52) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:892) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:419) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
```
Any way you could fix this? This seems to be a rather important bug here.
Thanks.

**Comment by ohylli** [comment]
I also have encountered this issue. Fortunately you can still start a run wit the older start command which still works even though it is not listed in the help output and help start does not give the instructions. For example to start a run with the watcher on ascension 5 you can give the command:

    start watcher 5

**Comment by Wensber** [comment]
Hello,
Sorry about this. Seems I didn't test my downfall fix properly.
I'll get this fixed.
Wensber
